TOKEN_URL: "https://energycurb.auth0.com/oauth/token"
CLIENT_ID: "iKAoRkr3qyFSnJSr3bodZRZZ6Hm3GqC3" # Official client_id from Curb #
CLIENT_SECRET: "dSoqbfwujF72a1DhwmjnqP4VAiBTqFt3WLLUtnpGDmCf6_CMQms3WEy8DxCQR3KY" # Official client_secret from Curb #
USERNAME: "YOUR-CURB-USERNAME" # Curb's login username/email information #
PASSWORD: "YOUR-CURB-PASSWORD" # Curb's password information #
AUDIENCE: "app.energycurb.com/api" 
MQTT_BROKER_URL: "mqtt://YOUR-MQTT-BROKER:1883" # MQTT Broker URL, default port 1883 #
MQTT_TOPIC: "home/curb/power" # You can change the topic to what ever you like it to be #
MQTT_USERNAME: "YOUR-MQTT-USERNAME"  # Leave empty if no username is needed #
MQTT_PASSWORD: "YOUR-MQTT-PASSWORD"  # Leave empty if no password is needed #
DEBUG: false # Set to true to enable output and debug messages #
HACONFIG: true #set to enable output of home assistant auto discover
PERSIST_TOKEN: false; # Persist the token to a file to avoid 429 errors while debugging (Recomended for debugging only) #
PERSIST_LAST_TOKEN: ""
PERSIST_LAST_REFRESH: "1900-01-01 00:00"